modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-only"
[[mods]]
modId="crime_gameplay_checks"
version="1"
displayName="MCA Crime gameplay client checks"
[[dependencies.crime_gameplay_checks]]
modId="mcacrime"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
[[dependencies.crime_gameplay_checks]]
modId="mca"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
