modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"
[[mods]]
modId="crime_justice_checks"
version="1"
displayName="MCA Crime village justice runtime checks"
[[dependencies.crime_justice_checks]]
modId="mcacrime"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="SERVER"
